[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "netlify-cloudinary"
  deliveryType = "upload"
  folder = "nextjs-app-500"

  [plugins.inputs.maxSize]
  width = 1200
  height = 1200
